style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/SSouik/docker-images
options:
  commits:
    filters:
      Type:
        - added
        - changed
        - refactor
        - fix
        - ci
        - docs
        - break
  commit_groups:
    title_maps:
      added: Added
      changed: Change
      refactor: Code Refactoring
      fix: Bug Fixes
      ci: CI & Build
      docs: Documentation
      break: Breaking Change
  header:
    pattern: "^(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE