name: Test Changelog

on:
  push:
    branches:
      - 'main'
jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    container:
      image: ssouik/git-chglog:latest
    steps:
      - name: Checkout code
        run: |
          git clone https://github.com/SSouik/docker-images.git code
          cd code
          git fetch
          git checkout ${GITHUB_HEAD_REF}
      - name: Generate Changelog
        run: |
          cd code
          generate-changelog \
            --config ".chglog/config.yml" \
            --template ".chglog/CHANGELOG.tpl.md" \
            --amend-commit
